#!/bin/bash
# Upgrade PKGSRC & Brew for macOS

# Upgrade PKGSRC
upgrade_pkgsrc() {
  echo '\nUpgrade PKGSRC:';
  sudo pkgin update && sudo pkgin upgrade;
}

# Upgrade Brew
upgrade_brew() {
 echo '\nUpgrade Brew:';
 brew update && brew upgrade;
}

# Run all upgrades
main() {
 upgrade_pkgsrc
 upgrade_brew
}

# Run main function
main
